### ISSUE TITLE
Unable to access Yellowdig community

### ISSUE THREAD

**Issue by ramacdo1** [Watts-College/cpp-524-spr-2022#2]
Good evening! I am having trouble accessing the Yellowdig community for this class, it keeps saying Page Not Found when I follow the link in Canvas (and the Github page redirects to Canvas). Is anyone else having this issue, or any suggestions on how to fix it? 
Perhaps Professor @BassettASU, do you know where I might be going wrong?

**Comment by BassettASU** [comment]
@ramacdo1 - this has been an ongoing issue and should now be solved on both Canvas and Github. Please see the announcement from the weekend for more detail as well.

**Comment by ramacdo1** [comment]
Thank you! The announcement was indeed mailed to me after I posted this question. Yellowdig is working for me now, thankfully!
