### ISSUE TITLE
Review Sessions

### ISSUE THREAD

**Issue by Sanaz-27** [Watts-College/cpp-524-spr-2022#3]
Hello Professor @BassettASU  & Professor @lecy,

I'm not sure if the Review Sessions are held live on Mondays? or at what time?
Checking the Github page for the Review Sessions, I can see that all the sessions have what I guess a pre-semester Review Sessions Videos?

Could you please clarify this?

Really appreciate it, 
Sana

**Comment by BassettASU** [comment]
Hi @Sanaz-27 
We are using video content from Professor Lecy from a previous semester as the content is still relevant. Please utilize our course syllabus for the schedule (not the video). For now, there are no weekly live sessions but you can contact me via this, Yellowdig, email, or book office hours to discuss any questions. 
Professor Bassett

**Comment by Sanaz-27** [comment]
Thank you for clarifying :)
