### ISSUE TITLE
Discussion 1 Playback Issues

### ISSUE THREAD

**Issue by trioptre** [Watts-College/cpp-524-spr-2022#4]
Anyone else having issues with the Discussion 1 video? Mine always freezes at about the 12:45 mark. I've tried on both Safari and Chrome but still experiencing issues...

https://mediaplus.asu.edu/lti/embedded?id=b80e8e35-fb3f-411e-a0d8-d1538db3d96c&siteId=61e0606e-415d-4001-8206-ffde48430c64

FYI @BassettASU and 
@u12345 

Thanks!

**Comment by BassettASU** [comment]
@trioptre - if you scrub through the video are you able to jump to another section and play? I am unable to replicate the freezing issue but have someone looking to see if it is a server issue. Is anyone else having the same issue?

**Comment by trioptre** [comment]
@BassettASU - Unfortunately I can only scrub up to 12:45. If I try to scrub past 12:45 I just get a blank screen. I also had this issue on my phone and iPad.

Thanks!

**Comment by BassettASU** [comment]
@trioptre - we are working to get this corrected with more reliable links. I will send out an update when those are ready, either tonight or tomorrow.

**Comment by BassettASU** [comment]
@trioptre - videos are up and working with greater playback functionality. Let me know if you have any issues and thank you for bringing this to our attention.
