### ISSUE TITLE
GitHub Course "Get Help" Section: "Get Office Hours" link broken

### ISSUE THREAD

**Issue by trioptre** [Watts-College/cpp-524-spr-2022#5]
On the ["Getting Help"](https://watts-college.github.io/cpp-524-spr-2022/help/) GitHub course page, the ["Get Office Hours" ](http://ds4ps.org/cpp-524-spr-2022 )link/button is not working. The link takes me to a 404 Not found error page.
[](url)

@BassettASU and/or @u12345 - Can you assist?

Thank you,
Dave

**Comment by u12345** [comment]
Professor. Bassett has to update that link. I don’t have access to that.
Ujitha S
________________________________
From: trioptre ***@***.***>
Sent: Wednesday, March 30, 2022 11:30 PM
To: Watts-College/cpp-524-spr-2022 ***@***.***>
Cc: Ujitha Senanayake ***@***.***>; Mention ***@***.***>
Subject: [Watts-College/cpp-524-spr-2022] GitHub Course "Get Help" Section: "Get Office Hours" link broken (Issue #5)


On the "Getting Help"<https://watts-college.github.io/cpp-524-spr-2022/help/> GitHub course page, the "Get Office Hours" <http://ds4ps.org/cpp-524-spr-2022> link/button is not working. The link takes me to a 404 Not found error page.
<url>

@BassettASU<https://github.com/BassettASU> and/or @u12345<https://github.com/u12345> - Can you assist?

Thank you,
Dave

**Comment by lecy** [comment]
If it’s not working the office hour info is on the course info page as well:

https://watts-college.github.io/cpp-524-spr-2022/

https://calendly.com/sarahbassettasu/office-hours?month=2022-03

**Comment by BassettASU** [comment]
@trioptre - I am still working to get this link issue solved but please do use the links posted above to book a time with me directly.
