### ISSUE TITLE
Example Final Project Submission

### ISSUE THREAD

**Issue by trioptre** [Watts-College/cpp-524-spr-2022#6]
Hi @BassettASU  - 

Is there an example final paper that we can reference for structure and format?

Thank You,
Dave

**Comment by BassettASU** [comment]
@trioptre - while a full final paper is not available, please reference [Course Schedule -> Research Design Memo](https://watts-college.github.io/cpp-524-spr-2022/schedule/#research-design-memo) for the final paper [instructions](https://raw.githubusercontent.com/Watts-College/cpp-524-fall-2021/main/final-project/final-paper-instructions.pdf), which includes requirements (use the list in this document as your table of contents).

**Comment by trioptre** [comment]
@BassettASU 

I'm not seeing the list you are referencing in the final paper instructions document. I can piece-together a table of contents using headers and re-phrasing certain sections from the document, but I don't see an actual list that I can use as my table of contents...

**Comment by trioptre** [comment]
@BassettASU 

With no example paper to compare to, I'll predominantly use bullet points and sub-bullet points to structure my document, if that's ok.

**Comment by BassettASU** [comment]
@trioptre - the list in the instructions is the numbered list of requirements that starts on page 1, ends on page 2 in the PDF instructions. Starting on page 3 is the very detailed breakdown of each section and what should be included (page 11 in the document shows the rubric, which you can also use as reference for your table of contents). The expectation is a written report and the first page is a memo, see page 10 in the instructions for an example. That is again located here: [instructions](https://raw.githubusercontent.com/Watts-College/cpp-524-fall-2021/main/final-project/final-paper-instructions.pdf)
