### ISSUE TITLE
Level of Confidence Measure

### ISSUE THREAD

**Issue by trioptre** [Watts-College/cpp-524-spr-2022#7]
@BassettASU 

How should we quantify our confidence level of the assumptions made in PART 1B - Theory of Change of the Final Paper instructions?

* Should we use a numeric scale (1-5)? Or a Likert-like scale (Not at All Confident/Somewhat Confident/Very Confident)?

**Comment by BassettASU** [comment]
@trioptre - good question. In terms of assessing level of confidence, you are not expected to quantify the level, but rather list and discuss the assumptions. The expectation is you will identify sensitivities to program implementation as a way to better understand potential program failure(s).
